import type { ProductWithImages, Category, ReviewWithProfile } from "@/types";

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    name: "Banarasi Silk",
    slug: "banarasi-silk",
    description: "Luxurious Banarasi silk sarees with intricate zari work, perfect for weddings and special occasions.",
    image_url: "/images/categories/banarasi.jpg",
    parent_id: null,
    sort_order: 1,
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
  },
  {
    id: "cat-2",
    name: "Kanjivaram",
    slug: "kanjivaram",
    description: "Traditional Kanjivaram sarees from Tamil Nadu, known for their rich colors and temple borders.",
    image_url: "/images/categories/kanjivaram.jpg",
    parent_id: null,
    sort_order: 2,
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
  },
  {
    id: "cat-3",
    name: "Chanderi",
    slug: "chanderi",
    description: "Lightweight Chanderi sarees with a sheer texture and elegant motifs.",
    image_url: "/images/categories/chanderi.jpg",
    parent_id: null,
    sort_order: 3,
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
  },
  {
    id: "cat-4",
    name: "Cotton",
    slug: "cotton",
    description: "Comfortable cotton sarees ideal for daily wear and casual outings.",
    image_url: "/images/categories/cotton.jpg",
    parent_id: null,
    sort_order: 4,
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
  },
  {
    id: "cat-5",
    name: "Georgette",
    slug: "georgette",
    description: "Flowing georgette sarees with modern prints and embellishments.",
    image_url: "/images/categories/georgette.jpg",
    parent_id: null,
    sort_order: 5,
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
  },
  {
    id: "cat-6",
    name: "Designer",
    slug: "designer",
    description: "Contemporary designer sarees with unique patterns and modern aesthetics.",
    image_url: "/images/categories/designer.jpg",
    parent_id: null,
    sort_order: 6,
    is_active: true,
    created_at: "2025-01-01T00:00:00Z",
    updated_at: "2025-01-01T00:00:00Z",
  },
];

function makeImages(productId: string, seed: number) {
  return [
    {
      id: `img-${productId}-1`,
      product_id: productId,
      url: `https://picsum.photos/seed/${seed}/400/533`,
      public_id: `${productId}-1`,
      alt_text: "Product image - front view",
      sort_order: 0,
      is_primary: true,
      width: 400,
      height: 533,
      created_at: "2025-01-01T00:00:00Z",
    },
    {
      id: `img-${productId}-2`,
      product_id: productId,
      url: `https://picsum.photos/seed/${seed + 100}/400/533`,
      public_id: `${productId}-2`,
      alt_text: "Product image - detail view",
      sort_order: 1,
      is_primary: false,
      width: 400,
      height: 533,
      created_at: "2025-01-01T00:00:00Z",
    },
    {
      id: `img-${productId}-3`,
      product_id: productId,
      url: `https://picsum.photos/seed/${seed + 200}/400/533`,
      public_id: `${productId}-3`,
      alt_text: "Product image - drape view",
      sort_order: 2,
      is_primary: false,
      width: 400,
      height: 533,
      created_at: "2025-01-01T00:00:00Z",
    },
  ];
}

export const MOCK_PRODUCTS: ProductWithImages[] = [
  {
    id: "prod-1",
    title: "Royal Banarasi Silk Wedding Saree",
    slug: "royal-banarasi-silk-wedding-saree",
    description: "This exquisite Banarasi silk saree features intricate gold zari work with traditional motifs. The rich maroon base is complemented by a stunning pallu with detailed craftsmanship that has been passed down through generations of master weavers.",
    short_description: "Handwoven Banarasi silk with gold zari work — perfect for weddings.",
    price: 12999,
    compare_at_price: 18999,
    category_id: "cat-1",
    status: "published",
    is_featured: true,
    material: "Pure Silk",
    color: "Maroon & Gold",
    occasion: "Wedding",
    work_type: "Zari Work",
    avg_rating: 4.8,
    review_count: 24,
    view_count: 450,
    meta_title: null,
    meta_description: null,
    created_at: "2025-03-01T00:00:00Z",
    updated_at: "2025-03-01T00:00:00Z",
    product_images: makeImages("prod-1", 10),
    categories: MOCK_CATEGORIES[0],
  },
  {
    id: "prod-2",
    title: "Classic Kanjivaram Temple Border Saree",
    slug: "classic-kanjivaram-temple-border-saree",
    description: "A timeless Kanjivaram saree with the iconic temple border design. Woven in deep emerald green with contrasting gold border, this saree is a must-have for every traditional wardrobe.",
    short_description: "Traditional Kanjivaram with temple border in emerald green.",
    price: 15499,
    compare_at_price: null,
    category_id: "cat-2",
    status: "published",
    is_featured: true,
    material: "Pure Silk",
    color: "Emerald Green",
    occasion: "Wedding",
    work_type: "Temple Border",
    avg_rating: 4.9,
    review_count: 18,
    view_count: 380,
    meta_title: null,
    meta_description: null,
    created_at: "2025-03-05T00:00:00Z",
    updated_at: "2025-03-05T00:00:00Z",
    product_images: makeImages("prod-2", 20),
    categories: MOCK_CATEGORIES[1],
  },
  {
    id: "prod-3",
    title: "Elegant Chanderi Silk Cotton Saree",
    slug: "elegant-chanderi-silk-cotton-saree",
    description: "A lightweight Chanderi saree in soft pastel pink with delicate floral butis. The sheer texture and subtle shimmer make it ideal for day events and festive gatherings.",
    short_description: "Lightweight Chanderi with floral motifs in pastel pink.",
    price: 4999,
    compare_at_price: 6999,
    category_id: "cat-3",
    status: "published",
    is_featured: true,
    material: "Silk Cotton",
    color: "Pastel Pink",
    occasion: "Festive",
    work_type: "Buti Work",
    avg_rating: 4.5,
    review_count: 12,
    view_count: 290,
    meta_title: null,
    meta_description: null,
    created_at: "2025-03-10T00:00:00Z",
    updated_at: "2025-03-10T00:00:00Z",
    product_images: makeImages("prod-3", 30),
    categories: MOCK_CATEGORIES[2],
  },
  {
    id: "prod-4",
    title: "Handloom Cotton Jamdani Saree",
    slug: "handloom-cotton-jamdani-saree",
    description: "A breezy handloom cotton saree with traditional Jamdani weaving. The white base with blue geometric patterns makes it perfect for everyday elegance and office wear.",
    short_description: "Pure cotton handloom with Jamdani motifs — breezy and elegant.",
    price: 3499,
    compare_at_price: null,
    category_id: "cat-4",
    status: "published",
    is_featured: true,
    material: "Pure Cotton",
    color: "White & Blue",
    occasion: "Daily Wear",
    work_type: "Jamdani",
    avg_rating: 4.3,
    review_count: 31,
    view_count: 520,
    meta_title: null,
    meta_description: null,
    created_at: "2025-03-12T00:00:00Z",
    updated_at: "2025-03-12T00:00:00Z",
    product_images: makeImages("prod-4", 40),
    categories: MOCK_CATEGORIES[3],
  },
  {
    id: "prod-5",
    title: "Printed Georgette Party Wear Saree",
    slug: "printed-georgette-party-wear-saree",
    description: "A stunning georgette saree with digital floral prints and a satin border. The vibrant teal shade and flowing drape make it the perfect choice for parties and receptions.",
    short_description: "Digital print georgette with satin border — party ready.",
    price: 2999,
    compare_at_price: 4499,
    category_id: "cat-5",
    status: "published",
    is_featured: true,
    material: "Georgette",
    color: "Teal",
    occasion: "Party",
    work_type: "Digital Print",
    avg_rating: 4.1,
    review_count: 8,
    view_count: 210,
    meta_title: null,
    meta_description: null,
    created_at: "2025-03-15T00:00:00Z",
    updated_at: "2025-03-15T00:00:00Z",
    product_images: makeImages("prod-5", 50),
    categories: MOCK_CATEGORIES[4],
  },
  {
    id: "prod-6",
    title: "Designer Sequin Embroidered Saree",
    slug: "designer-sequin-embroidered-saree",
    description: "A contemporary designer saree with heavy sequin embroidery on a net base. The midnight blue color with silver sequin work creates a dazzling effect perfect for cocktail parties.",
    short_description: "Sequin embroidered net saree in midnight blue.",
    price: 8999,
    compare_at_price: 11999,
    category_id: "cat-6",
    status: "published",
    is_featured: true,
    material: "Net",
    color: "Midnight Blue",
    occasion: "Party",
    work_type: "Sequin Embroidery",
    avg_rating: 4.7,
    review_count: 15,
    view_count: 340,
    meta_title: null,
    meta_description: null,
    created_at: "2025-03-18T00:00:00Z",
    updated_at: "2025-03-18T00:00:00Z",
    product_images: makeImages("prod-6", 60),
    categories: MOCK_CATEGORIES[5],
  },
  {
    id: "prod-7",
    title: "Banarasi Organza Floral Saree",
    slug: "banarasi-organza-floral-saree",
    description: "A modern take on the classic Banarasi with organza fabric and floral jaal pattern. Light as a feather with a luxurious sheen, ideal for daytime celebrations.",
    short_description: "Organza Banarasi with floral jaal — lightweight luxury.",
    price: 7499,
    compare_at_price: null,
    category_id: "cat-1",
    status: "published",
    is_featured: false,
    material: "Organza",
    color: "Peach",
    occasion: "Festive",
    work_type: "Jaal Work",
    avg_rating: 4.4,
    review_count: 9,
    view_count: 180,
    meta_title: null,
    meta_description: null,
    created_at: "2025-03-20T00:00:00Z",
    updated_at: "2025-03-20T00:00:00Z",
    product_images: makeImages("prod-7", 70),
    categories: MOCK_CATEGORIES[0],
  },
  {
    id: "prod-8",
    title: "Pure Linen Handblock Print Saree",
    slug: "pure-linen-handblock-print-saree",
    description: "A natural linen saree with traditional handblock prints in earthy tones. Breathable and eco-friendly, this saree combines comfort with artisan craftsmanship.",
    short_description: "Handblock printed linen saree in earthy tones.",
    price: 4299,
    compare_at_price: 5499,
    category_id: "cat-4",
    status: "published",
    is_featured: false,
    material: "Linen",
    color: "Earthy Brown",
    occasion: "Casual",
    work_type: "Block Print",
    avg_rating: 4.6,
    review_count: 22,
    view_count: 410,
    meta_title: null,
    meta_description: null,
    created_at: "2025-03-22T00:00:00Z",
    updated_at: "2025-03-22T00:00:00Z",
    product_images: makeImages("prod-8", 80),
    categories: MOCK_CATEGORIES[3],
  },
  {
    id: "prod-9",
    title: "Tussar Silk Kalamkari Saree",
    slug: "tussar-silk-kalamkari-saree",
    description: "A handpainted Kalamkari saree on luxurious Tussar silk base. Each piece is a work of art, featuring mythological scenes and natural dye colors.",
    short_description: "Handpainted Kalamkari on Tussar silk — wearable art.",
    price: 6799,
    compare_at_price: null,
    category_id: "cat-6",
    status: "published",
    is_featured: true,
    material: "Tussar Silk",
    color: "Natural & Red",
    occasion: "Festive",
    work_type: "Kalamkari",
    avg_rating: 4.9,
    review_count: 7,
    view_count: 160,
    meta_title: null,
    meta_description: null,
    created_at: "2025-03-25T00:00:00Z",
    updated_at: "2025-03-25T00:00:00Z",
    product_images: makeImages("prod-9", 90),
    categories: MOCK_CATEGORIES[5],
  },
  {
    id: "prod-10",
    title: "Kanjivaram Checks & Stripes Saree",
    slug: "kanjivaram-checks-stripes-saree",
    description: "A contemporary Kanjivaram saree featuring bold checks and stripes pattern. The royal purple base with golden checks offers a modern twist on tradition.",
    short_description: "Bold checks Kanjivaram in royal purple & gold.",
    price: 13999,
    compare_at_price: 16999,
    category_id: "cat-2",
    status: "published",
    is_featured: false,
    material: "Pure Silk",
    color: "Royal Purple",
    occasion: "Wedding",
    work_type: "Checks & Stripes",
    avg_rating: 4.5,
    review_count: 11,
    view_count: 270,
    meta_title: null,
    meta_description: null,
    created_at: "2025-04-01T00:00:00Z",
    updated_at: "2025-04-01T00:00:00Z",
    product_images: makeImages("prod-10", 15),
    categories: MOCK_CATEGORIES[1],
  },
  {
    id: "prod-11",
    title: "Chiffon Saree with Sequin Border",
    slug: "chiffon-saree-sequin-border",
    description: "A graceful chiffon saree in soft lavender with a delicate sequin border. Perfect for evening events where you want to look effortlessly glamorous.",
    short_description: "Soft chiffon with sequin border in lavender.",
    price: 3299,
    compare_at_price: null,
    category_id: "cat-5",
    status: "published",
    is_featured: false,
    material: "Chiffon",
    color: "Lavender",
    occasion: "Party",
    work_type: "Sequin Border",
    avg_rating: 4.2,
    review_count: 5,
    view_count: 130,
    meta_title: null,
    meta_description: null,
    created_at: "2025-04-05T00:00:00Z",
    updated_at: "2025-04-05T00:00:00Z",
    product_images: makeImages("prod-11", 25),
    categories: MOCK_CATEGORIES[4],
  },
  {
    id: "prod-12",
    title: "Chanderi Zari Border Daily Wear Saree",
    slug: "chanderi-zari-border-daily-wear",
    description: "An everyday Chanderi saree with a subtle zari border. The sky blue color and lightweight drape make it comfortable for all-day wear while still looking put-together.",
    short_description: "Everyday Chanderi with zari border in sky blue.",
    price: 3999,
    compare_at_price: 4999,
    category_id: "cat-3",
    status: "published",
    is_featured: true,
    material: "Chanderi",
    color: "Sky Blue",
    occasion: "Daily Wear",
    work_type: "Zari Border",
    avg_rating: 4.0,
    review_count: 16,
    view_count: 350,
    meta_title: null,
    meta_description: null,
    created_at: "2025-04-08T00:00:00Z",
    updated_at: "2025-04-08T00:00:00Z",
    product_images: makeImages("prod-12", 35),
    categories: MOCK_CATEGORIES[2],
  },
];

export const MOCK_REVIEWS: ReviewWithProfile[] = [
  {
    id: "rev-1",
    product_id: "prod-1",
    user_id: "user-1",
    rating: 5,
    title: "Absolutely stunning!",
    comment: "The zari work is incredible and the silk quality is top-notch. Wore it for my sister's wedding and got so many compliments. Worth every rupee!",
    status: "approved",
    admin_response: "Thank you for your kind words! We're glad you loved the saree.",
    created_at: "2025-04-01T00:00:00Z",
    updated_at: "2025-04-01T00:00:00Z",
    profiles: { full_name: "Priya Sharma", avatar_url: null },
  },
  {
    id: "rev-2",
    product_id: "prod-1",
    user_id: "user-2",
    rating: 5,
    title: "Beautiful craftsmanship",
    comment: "The saree is exactly as shown in the pictures. The weaving is exquisite and the color is rich. Highly recommended for anyone looking for an authentic Banarasi.",
    status: "approved",
    admin_response: null,
    created_at: "2025-04-10T00:00:00Z",
    updated_at: "2025-04-10T00:00:00Z",
    profiles: { full_name: "Anita Patel", avatar_url: null },
  },
  {
    id: "rev-3",
    product_id: "prod-1",
    user_id: "user-3",
    rating: 4,
    title: "Great saree, slightly heavy",
    comment: "Beautiful saree with intricate work. Only giving 4 stars because it's a bit heavier than expected, but the quality makes up for it. Would buy again.",
    status: "approved",
    admin_response: null,
    created_at: "2025-04-15T00:00:00Z",
    updated_at: "2025-04-15T00:00:00Z",
    profiles: { full_name: "Meena Reddy", avatar_url: null },
  },
  {
    id: "rev-4",
    product_id: "prod-4",
    user_id: "user-4",
    rating: 5,
    title: "Perfect for daily wear",
    comment: "So comfortable! The cotton is soft and breathable, and the Jamdani work adds a touch of elegance. Great for office wear.",
    status: "approved",
    admin_response: null,
    created_at: "2025-04-20T00:00:00Z",
    updated_at: "2025-04-20T00:00:00Z",
    profiles: { full_name: "Kavita Joshi", avatar_url: null },
  },
  {
    id: "rev-5",
    product_id: "prod-4",
    user_id: "user-5",
    rating: 4,
    title: "Love the fabric",
    comment: "The handloom quality is evident. Colors are exactly as shown. Fast delivery too!",
    status: "approved",
    admin_response: "Thank you for the review! We take pride in our handloom collection.",
    created_at: "2025-04-25T00:00:00Z",
    updated_at: "2025-04-25T00:00:00Z",
    profiles: { full_name: "Deepa Nair", avatar_url: null },
  },
];
