import { EmptyState } from "@/components/shared/empty-state";
import { Mail, MessageCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { getAdminMessages } from "@/lib/queries/messages";
import { getWhatsAppLogs } from "@/lib/queries/loyalty";

const WHATSAPP_KIND_LABEL: Record<string, string> = {
  order: "Order",
  inquiry_reopen: "Order re-opened",
  unboxing: "Unboxing video",
  share: "Product share",
  support: "Support",
};

export default async function AdminMessagesPage() {
  const [messages, whatsappLogs] = await Promise.all([
    getAdminMessages(),
    getWhatsAppLogs(),
  ]);

  return (
    <div>
      <h1 className="text-2xl font-bold">Messages</h1>
      <p className="mt-1 text-sm text-muted-foreground">
        Contact form submissions and the WhatsApp message audit log.
      </p>

      <div className="mt-6">
        {!messages || messages.length === 0 ? (
          <EmptyState
            icon={Mail}
            title="No messages yet"
            description="Messages from the contact form will appear here."
          />
        ) : (
          <div className="space-y-3">
            {messages.map(
              (msg: {
                id: string;
                name: string;
                email: string;
                subject: string | null;
                message: string;
                is_read: boolean;
                created_at: string;
              }) => (
                <div
                  key={msg.id}
                  className="rounded-lg border bg-card p-4"
                >
                  <div className="flex items-start justify-between">
                    <div>
                      <p className="font-medium">{msg.name}</p>
                      <p className="text-sm text-muted-foreground">
                        {msg.email}
                      </p>
                    </div>
                    <div className="flex items-center gap-2">
                      {!msg.is_read && <Badge>New</Badge>}
                      <span className="text-xs text-muted-foreground">
                        {new Date(msg.created_at).toLocaleDateString("en-IN")}
                      </span>
                    </div>
                  </div>
                  {msg.subject && (
                    <p className="mt-2 text-sm font-medium">{msg.subject}</p>
                  )}
                  <p className="mt-1 text-sm text-muted-foreground">
                    {msg.message}
                  </p>
                </div>
              )
            )}
          </div>
        )}
      </div>

      <div className="mt-10">
        <h2 className="text-lg font-semibold">WhatsApp message log</h2>
        <p className="mt-1 text-sm text-muted-foreground">
          Every WhatsApp message generated by the site (orders, shares,
          unboxing submissions). wa.me links carry no delivery receipts, so the
          recorded status is that the message link was generated — delivery
          confirmation would require the WhatsApp Business API.
        </p>
        <div className="mt-4">
          {whatsappLogs.length === 0 ? (
            <EmptyState
              icon={MessageCircle}
              title="No WhatsApp messages logged yet"
              description="Messages appear here when customers start orders or share products."
            />
          ) : (
            <div className="space-y-2">
              {whatsappLogs.map((log) => (
                <details key={log.id} className="rounded-lg border bg-card p-3">
                  <summary className="flex cursor-pointer list-none items-center justify-between gap-2 text-sm">
                    <span className="flex min-w-0 items-center gap-2">
                      <Badge variant="secondary" className="shrink-0 text-xs">
                        {WHATSAPP_KIND_LABEL[log.kind] ?? log.kind}
                      </Badge>
                      <span className="truncate font-medium">
                        {log.profiles?.full_name ??
                          log.profiles?.username ??
                          "Guest"}
                      </span>
                      <span className="truncate text-muted-foreground">
                        {log.message.split("\n")[0]}
                      </span>
                    </span>
                    <span className="shrink-0 text-xs text-muted-foreground">
                      {new Date(log.created_at).toLocaleDateString("en-IN", {
                        month: "short",
                        day: "numeric",
                        hour: "2-digit",
                        minute: "2-digit",
                      })}
                    </span>
                  </summary>
                  <pre className="mt-2 rounded bg-muted p-2 text-xs whitespace-pre-wrap">
                    {log.message}
                  </pre>
                  <p className="mt-1 text-xs text-muted-foreground">
                    Status: {log.status === "link_generated" ? "link generated" : log.status}
                  </p>
                </details>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
